#!/usr/bin/env bash

## run make with 120% of core jobs for maximum performance
realnum=`cat /proc/cpuinfo | grep cores | wc -l `
let bestnum=$realnum+$(printf %.0f `echo "$realnum*0.2"|bc`)
make -j`echo $bestnum` $*